### ISSUE TITLE
Remove need to enter full paths when live-upgrading...

### ISSUE THREAD

**Issue by sjaymin1001** [Magisk-Modules-Repo/acc#1]
Hey @VR-25,

I'd like to let you know that to remove the need to enter full path after live-upgrading, you can link all binaries back to /sbin, which is in $PATH, so should work. And if you copy those files directly to /sbin instead of /dev, you can also prevent some root detection methods looking in /dev for unwanted file/folders. Anyways, it's all upto you. I figured I'd let you know of the possibilities.

**Comment by VR-25** [comment]
Sure, but I didn't use /sbin right away because it's not in my default PATH (only /sbin/su). Could you confirm that `resetprop` can be executed without changing PATH first? My Termux could be messed up.
