### ISSUE TITLE
Broken URL in README.md

### ISSUE THREAD

**Issue by dagaz** [Magisk-Modules-Repo/acc#10]
Hi!

It seems the URL for 
`Must read - how to prolong lithium ion batteries lifespan`
has changed. 

If my search was correct, the current URL might be:
https://batteryuniversity.com/article/bu-808-how-to-prolong-lithium-based-batteries

**Comment by VR-25** [comment]
The website changed in the last couple of mounts.
Will update the links.
Thanks.
#4
