### ISSUE TITLE
100% CPU usage when `acc -e`

### ISSUE THREAD

**Issue by kmvan** [Magisk-Modules-Repo/acc#12]
OS: Android 8.1 Los 15.1
Phone: HTC U11 6+128
Modules: Busybox + acc

When I type `acc -e` after su, the CPU is working 100% and acc does not work any feature.

![Screenshot_Termux_20190414-152021](https://user-images.githubusercontent.com/3839554/56089728-eb433b00-5ec9-11e9-9527-857cd0a80d6e.png)

**Comment by VR-25** [comment]
Strange
`accd` does run in the background, but `acc -e` doesn't.

What's the output of `acc -s`?

**Comment by kmvan** [comment]
`acc -s` shows some infomation of success.
I can't provide more detailed information because I flashed Pie.
Looks not work for my phone. I will make some tests.
Thanks, the great module.
