### ISSUE TITLE
Documentation problem (acc and the acc app)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Magisk-Modules-Repo/acc#2]
I find the difference between acc and the 'acc app' - a difference your frontpage (https://github.com/Magisk-Modules-Repo/acc) invokes - confusing. Also, you advise users who are not comfortable with the command line to . . use curl to download the 'acc app' from Github. On a phone.

Android Lollipop
ACC 1,3,1
I have Termux.

**Comment by VR-25** [comment]
ACCApp is a frontend - it won't work without ACC.

You misunderstood the [NOTES/TIPS FOR FRONT-END DEVELOPERS(https://github.com/Magisk-Modules-Repo/acc#notestips-for-front-end-developers) section.

Regarding `curl` - it can be used **by the app** to download the [acc installer](https://raw.githubusercontent.com/Magisk-Modules-Repo/acc/master/install-latest.sh). I didn't suggest downloading the app with curl!

**Comment by LinuxOnTheDesktop** [comment]
> You misunderstood

That was, more or less, my point. Anyhow, I have given up on acc (and/or ACCApp . .). Thanks anyway.
