### ISSUE TITLE
Problem editing and even locating the config file

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Magisk-Modules-Repo/acc#3]
Currently I cannot locate the config.txt file. I did have an `acc` folder, but even as root I couldn't get access to it. So I removed acc and reinstalled it. And now I cannot find any `acc` folder at all or even the logs folder. Still, some or all of that might be my fault; I am comfortable with Linux and with Bash but the Android file system is something of a mystery to me and trying to use a terminal on a small phone is not something I find easy.

Android Lollipop
ACC 1,3,1
I have Termux, and can if necessary connect my phone to a Linux computer, with USB debugging enabled.

**Comment by VR-25** [comment]
https://github.com/VR-25/acc/releases/
Have you tried the latest version?

**Comment by LinuxOnTheDesktop** [comment]
No.  I have given up on acc (and/or ACCApp . .). Thanks anyway.
