### ISSUE TITLE
Calling problem occurs

### ISSUE THREAD

**Issue by Hadiuzzaman18** [Magisk-Modules-Repo/acc#6]
Calls can't be made after a reboot of latest module..
Showing calls can't be make because there are no calling account but deleting module makes everything normal ...
Please fix it
![Screenshot_2020-07-29-03-46-43-341_com android server telecom](https://user-images.githubusercontent.com/68928666/88729137-fcfb3100-d154-11ea-8c91-35e9a31c639d.jpg)

**Comment by VR-25** [comment]
It's been a while.
Try the latest version to see how it goes.
Most likely, this is an issue related a particular charging switch.
Try another switch (`acc -ss`) after knowing which ones work (`acc -t`).

I'll close this now.
Please refer to #1.
If the issue persist, open another issue in the main repository.
Thanks.
