### ISSUE TITLE
An acc mode for long-term plugged power?

### ISSUE THREAD

**Issue by Justsoos** [Magisk-Modules-Repo/acc#6]
I have a phone running with plugged AC adapter always, and battery is like the UPS for small current supply in case the AC power not enough.

So, could acc set a mode to shutdown the battery charging and provide the full AC power supply when battery is up a level like 60%, and both charging and AC supply beneath a level like 40% till 80%? also saving the life of battery.

And it is wide using for mobile gamer or video monitor, etc.

**Comment by VR-25** [comment]
There are two presets for that: endurance+ (40-41%) and endurance (59-60%).
acc -s endurance (or 5960)
acc -s endurance+ (or 4041)

Some devices put the battery on idle and draw power directly from the external power supply once charging is disabled. Regardless, these presets will help.

In the next version, users will be able to easily control the charging voltage, which is much better than limiting capacity. You want 3.92 Volts for endurance (heavy usage while plugged in).
