### ISSUE TITLE
Not working with latest update on OnePlus 7T

### ISSUE THREAD

**Issue by rdonnelly2** [Magisk-Modules-Repo/acc#8]
With the latest version of ACC and Oxygen OS 10.0.05.HD65AA. The phone charges to 100%, I have capacity set to (-1 60 77 80 false)

Also a question, on resetBattStats=(false false) do I change both falses to true to make this happen?

**Comment by VR-25** [comment]
Here's what those two values refer to: `resetBattStats=(reset_batt_stats_on_pause reset_batt_stats_on_unplug)`
#4
