### ISSUE TITLE
Adaptive charging

### ISSUE THREAD

**Issue by gitati16** [Magisk-Modules-Repo/acc#9]
Hi, I read in early December that Google introduced a feature called adaptive charging for their Pixel phones.
https://support.google.com/pixelphone/answer/7106961?hl=en
Is it possible to introduce this functionality into the software?

**Comment by VR-25** [comment]
Hello,
Although it's not automatic, you can already use this feature.
Enabling it at this point, requires some light programming, though.
Once I'm done updating another project of mine - Daily Job Schedule - you'll be able to easily schedule adaptive charging.
#4
