### ISSUE TITLE
fail to upgrade to 2019.3.3-r1

### ISSUE THREAD

**Issue by Justsoos** [Magisk-Modules-Repo/acc#9]
the log:
[magisk_install_log_20190304_051457.log](https://github.com/Magisk-Modules-Repo/acc/files/2923701/magisk_install_log_20190304_051457.log)
[acc-power_supply-virgo.log](https://github.com/Magisk-Modules-Repo/acc/files/2923704/acc-power_supply-virgo.log)

**Comment by VR-25** [comment]
Does the command `find /sys/devices '(' '(' -type f -o -type d ')' -a '(' -ipath '*batt*' -o -ipath '*ch*rg*' -o -ipath '*power_supply*' ')' ')' -print` fail if you run it manually (as root)?

**Comment by Justsoos** [comment]
so, it was a bug of ver 2019.3.3-r1？
today ver 201903070 installation works well

**Comment by VR-25** [comment]
Yes
Enjoy
